spring:
  application:
    name: bablog-be
  mvc:
    static-path-pattern: /static/**
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/bablog_db
    username: root
    password: bablog2513
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: mySecretKey1234mySecretKey1234mySecretKey1234mySecretKey1234mySecretKey1234mySecretKey1234mySecretKey1234
  expiration: 3600000

